package com.mochi.keyboard.ime.render

/** Batch 2.0 built-in themes, machine-ported from iOS's
 * `BuiltInThemes+Batch2.swift` (same source of truth, same token values, same art). */
object BuiltInThemesBatch2 {
    val all: List<MochiKeyboardTheme> get() = listOf(auroraWinterWonderland, cozyCountrysideFarm, lavenderMoonGarden, magentaMidnightGlow, midnightOceanVoyage, moonlitMagic, mysticGreenHaven, royalSunsetAtelier, vintageWriterEvening, zenGarden, autumnCozyCottage, cozyCottagecoreStudio, enchantedGardenCafe, enchantedWitchyNight, kawaiiStrawberryDream, lavenderParisNight, matchaGarden, mermaidDreamscape, midnightCafe, moonlitBeachEscape, starlitDreamCafe)

    val auroraWinterWonderland: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.aurora-winter-wonderland",
            name = "Aurora Winter Wonderland",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#C9CAFF"), ThemeColor.hex("#BFBFF5"), ThemeColor.hex("#B7B7ED"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_aurora_winter_wonderland", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#8895BA").withAlpha(0.46), ThemeColor.hex("#8895BA").withAlpha(0.34))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#C2D0F7").withAlpha(0.73), ThemeColor.hex("#BBC9EE").withAlpha(0.73))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B6C3E7").withAlpha(0.85), ThemeColor.hex("#AEBADD").withAlpha(0.85))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FCFDFF").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#BAC7ED").withAlpha(0.79), ThemeColor.hex("#B3BFE3").withAlpha(0.79))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#ACB9DB").withAlpha(0.91), ThemeColor.hex("#A4B0D1").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#F4F6FC").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#C2D0F7").withAlpha(0.79), ThemeColor.hex("#BBC9EE").withAlpha(0.79))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B6C3E7").withAlpha(0.91), ThemeColor.hex("#AEBADD").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FCFDFF").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#C2D0F7").withAlpha(0.42), ThemeColor.hex("#BBC9EE").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B7C4E9").withAlpha(0.42), ThemeColor.hex("#B0BCDF").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FCFDFF").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 15.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_aww_", heightFraction = 0.46, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val cozyCountrysideFarm: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.cozy-countryside-farm",
            name = "Cozy Countryside Farm",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#D5D0A4"), ThemeColor.hex("#CAC59A"), ThemeColor.hex("#C2BD92"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_cozy_countryside_farm", scalesToFill = true, verticalAnchor = 0.3), scrim = ThemeScrim(ThemeColor.hex("#A29D5D").withAlpha(0.18), ThemeColor.hex("#A29D5D").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D5D7A8"), ThemeColor.hex("#CECFA3"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C7C99E"), ThemeColor.hex("#BFC197"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#959676").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CCCEA1"), ThemeColor.hex("#C4C69B"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#BEBF96"), ThemeColor.hex("#B5B78F"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#8E9071").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#DAD793"), ThemeColor.hex("#D2CF8E"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CCC98A"), ThemeColor.hex("#C3C184"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#989667").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D5D7A8").withAlpha(0.42), ThemeColor.hex("#CECFA3").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C9CB9F").withAlpha(0.42), ThemeColor.hex("#C1C399").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FDFDFB").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 11.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_ccf_", heightFraction = 0.52, bottomInsetFraction = 0.10, opacity = 0.90, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
    val lavenderMoonGarden: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.lavender-moon-garden",
            name = "Lavender Moon Garden",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#4E3D4B"), ThemeColor.hex("#71505D"), ThemeColor.hex("#473745"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_lavender_moon_garden", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#7D5F74").withAlpha(0.18), ThemeColor.hex("#7D5F74").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CFAABA"), ThemeColor.hex("#BA97B6"))), labelColor = ThemeColor.hex("#000000"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#BB9AA8"), ThemeColor.hex("#A385A0"))), pressedLabelColor = ThemeColor.hex("#000000"), border = ThemeBorder(ThemeColor.hex("#F0E5EA").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F8F3F5").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#C1A0B4"), ThemeColor.hex("#AA8D9E"))), labelColor = ThemeColor.hex("#000000"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#AC8FA0"), ThemeColor.hex("#907886"))), pressedLabelColor = ThemeColor.hex("#000000"), border = ThemeBorder(ThemeColor.hex("#E9DEE5").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F2ECF0").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#C3B0B9"), ThemeColor.hex("#AE9DA6"))), labelColor = ThemeColor.hex("#000000"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B09FA8"), ThemeColor.hex("#998A91"))), pressedLabelColor = ThemeColor.hex("#000000"), border = ThemeBorder(ThemeColor.hex("#EDE7EA").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F7F4F5").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CFAABA").withAlpha(0.42), ThemeColor.hex("#BA97B6").withAlpha(0.42))), labelColor = ThemeColor.hex("#000000").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#BE9CAA").withAlpha(0.42), ThemeColor.hex("#A687A2").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#F0E5EA").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 16.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_lmg_", heightFraction = 0.48, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val magentaMidnightGlow: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.magenta-midnight-glow",
            name = "Magenta Midnight Glow",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#59384C"), ThemeColor.hex("#7D486A"), ThemeColor.hex("#523245"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_magenta_midnight_glow", scalesToFill = true, verticalAnchor = 0.52), scrim = ThemeScrim(ThemeColor.hex("#600F35").withAlpha(0.20), ThemeColor.hex("#600F35").withAlpha(0.06))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#48092E"), ThemeColor.hex("#5E2647"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#7F536D"), ThemeColor.hex("#875D75"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D2C2CB").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#CCBAC4").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#D2C2CB").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#6C3956"), ThemeColor.hex("#764762"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#8E667D"), ThemeColor.hex("#946F84"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D8CBD2").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#D2C2CB").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#D8CBD2").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#431323"), ThemeColor.hex("#582D3B"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#795762"), ThemeColor.hex("#81616C"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D0C4C8").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#C9BBC0").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#D0C4C8").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#48092E").withAlpha(0.50), ThemeColor.hex("#5E2647").withAlpha(0.50))), labelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#784965").withAlpha(0.50), ThemeColor.hex("#81556E").withAlpha(0.50))), border = ThemeBorder(ThemeColor.hex("#CCBAC4").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#CCBAC4").withAlpha(0.28), cornerRadiusOverrideDp = 14.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mmg_", heightFraction = 0.44, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val midnightOceanVoyage: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.midnight-ocean-voyage",
            name = "Midnight Ocean Voyage",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#3E4346"), ThemeColor.hex("#4E5B61"), ThemeColor.hex("#383D3F"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_midnight_ocean_voyage", scalesToFill = true, verticalAnchor = 0.62), scrim = ThemeScrim(ThemeColor.hex("#192A29").withAlpha(0.20), ThemeColor.hex("#192A29").withAlpha(0.06))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#051418"), ThemeColor.hex("#273337"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#535D60"), ThemeColor.hex("#5D676A"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#C2C5C6").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#B9BDBE").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#C2C5C6").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#394548"), ThemeColor.hex("#475255"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#677072"), ThemeColor.hex("#6F787A"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#CACDCE").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#C2C5C6").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#CACDCE").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#051418"), ThemeColor.hex("#273337"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#535D60"), ThemeColor.hex("#5D676A"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#C2C5C6").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#B9BDBE").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#C2C5C6").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#051418").withAlpha(0.50), ThemeColor.hex("#273337").withAlpha(0.50))), labelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#4A5558").withAlpha(0.50), ThemeColor.hex("#555F62").withAlpha(0.50))), border = ThemeBorder(ThemeColor.hex("#B9BDBE").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#B9BDBE").withAlpha(0.28), cornerRadiusOverrideDp = 14.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mov_", heightFraction = 0.44, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val moonlitMagic: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.moonlit-magic",
            name = "Moonlit Magic",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#47413D"), ThemeColor.hex("#68554F"), ThemeColor.hex("#413B36"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_moonlit_magic", scalesToFill = true, verticalAnchor = 0.55), scrim = ThemeScrim(ThemeColor.hex("#9F8259").withAlpha(0.46), ThemeColor.hex("#9F8259").withAlpha(0.34))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E0C185").withAlpha(0.73), ThemeColor.hex("#D6B980").withAlpha(0.73))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CFB27B").withAlpha(0.85), ThemeColor.hex("#C4A975").withAlpha(0.85))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#F9F4E9").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D5B77F").withAlpha(0.79), ThemeColor.hex("#CBAF79").withAlpha(0.79))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C2A774").withAlpha(0.91), ThemeColor.hex("#B79E6D").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#F4ECDD").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FBF9F3").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E0C185").withAlpha(0.79), ThemeColor.hex("#D6B980").withAlpha(0.79))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CFB27B").withAlpha(0.91), ThemeColor.hex("#C4A975").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#F9F4E9").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E0C185").withAlpha(0.42), ThemeColor.hex("#D6B980").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D1B47C").withAlpha(0.42), ThemeColor.hex("#C6AB76").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#F9F4E9").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 15.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mlm_", heightFraction = 0.46, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val mysticGreenHaven: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.mystic-green-haven",
            name = "Mystic Green Haven",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#DBCEAA"), ThemeColor.hex("#D0C39F"), ThemeColor.hex("#C8BB97"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_mystic_green_haven", scalesToFill = true, verticalAnchor = 0.55), scrim = ThemeScrim(ThemeColor.hex("#A99A71").withAlpha(0.18), ThemeColor.hex("#A99A71").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E4D3A5"), ThemeColor.hex("#DCCC9F"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D5C69B"), ThemeColor.hex("#CDBE95"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FEFDFA").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.34), cornerRadiusOverrideDp = 8.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.70), bevelWidth = 1.00, bevelFalloff = 0.10, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.16, innerShadowRadius = 2.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#DACB9E"), ThemeColor.hex("#D2C398"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CBBC93"), ThemeColor.hex("#C2B48D"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FBF9F4").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.34), cornerRadiusOverrideDp = 8.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.70), bevelWidth = 1.00, bevelFalloff = 0.10, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.16, innerShadowRadius = 2.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E4D3A5"), ThemeColor.hex("#DCCC9F"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D5C69B"), ThemeColor.hex("#CDBE95"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FEFDFA").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.34), cornerRadiusOverrideDp = 8.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.70), bevelWidth = 1.00, bevelFalloff = 0.10, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.16, innerShadowRadius = 2.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E4D3A5").withAlpha(0.42), ThemeColor.hex("#DCCC9F").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D7C89C").withAlpha(0.42), ThemeColor.hex("#CFC096").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FEFDFA").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.34), cornerRadiusOverrideDp = 10.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mgh_", heightFraction = 0.46, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val royalSunsetAtelier: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.royal-sunset-atelier",
            name = "Royal Sunset Atelier",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#513E3B"), ThemeColor.hex("#70524F"), ThemeColor.hex("#4A3834"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_royal_sunset_atelier", scalesToFill = true, verticalAnchor = 0.42), scrim = ThemeScrim(ThemeColor.hex("#47170C").withAlpha(0.18), ThemeColor.hex("#47170C").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#340D08"), ThemeColor.hex("#5D3E3A"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#725754"), ThemeColor.hex("#826A67"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#CDC3C2").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#C6BBBA").withAlpha(0.34), cornerRadiusOverrideDp = 8.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#CDC3C2").withAlpha(0.70), bevelWidth = 1.00, bevelFalloff = 0.10, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.16, innerShadowRadius = 2.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#5D3E3A"), ThemeColor.hex("#725754"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#826A67"), ThemeColor.hex("#8F7A77"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D4CBCA").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#CDC3C2").withAlpha(0.34), cornerRadiusOverrideDp = 8.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#D4CBCA").withAlpha(0.70), bevelWidth = 1.00, bevelFalloff = 0.10, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.16, innerShadowRadius = 2.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#330E08"), ThemeColor.hex("#5C3E3A"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#715753"), ThemeColor.hex("#816A67"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#CDC3C2").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#C5BBB9").withAlpha(0.34), cornerRadiusOverrideDp = 8.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#CDC3C2").withAlpha(0.70), bevelWidth = 1.00, bevelFalloff = 0.10, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.16, innerShadowRadius = 2.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#340D08").withAlpha(0.50), ThemeColor.hex("#5D3E3A").withAlpha(0.50))), labelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#6B4E4B").withAlpha(0.50), ThemeColor.hex("#7C6360").withAlpha(0.50))), border = ThemeBorder(ThemeColor.hex("#C6BBBA").withAlpha(0.55), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.26, 1.60, 1.60), topHighlight = ThemeColor.hex("#C6BBBA").withAlpha(0.34), cornerRadiusOverrideDp = 10.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_rsa_", heightFraction = 0.46, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val vintageWriterEvening: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.vintage-writer-evening",
            name = "Vintage Writer Evening",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#503F31"), ThemeColor.hex("#655747"), ThemeColor.hex("#49392A"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_vintage_writer_evening", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#A17945").withAlpha(0.16), ThemeColor.hex("#A17945").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#DCAD67"), ThemeColor.hex("#D4A764"))), labelColor = ThemeColor.hex("#19141D"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C79D5E"), ThemeColor.hex("#BE965A"))), pressedLabelColor = ThemeColor.hex("#19141D"), border = ThemeBorder(ThemeColor.hex("#19141D").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CEA261"), ThemeColor.hex("#C69C5D"))), labelColor = ThemeColor.hex("#19141D"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B89157"), ThemeColor.hex("#AE8952"))), pressedLabelColor = ThemeColor.hex("#19141D"), border = ThemeBorder(ThemeColor.hex("#19141D").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#DCAD67"), ThemeColor.hex("#D4A764"))), labelColor = ThemeColor.hex("#19141D"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C79D5E"), ThemeColor.hex("#BE965A"))), pressedLabelColor = ThemeColor.hex("#19141D"), border = ThemeBorder(ThemeColor.hex("#19141D").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#DCAD67").withAlpha(0.42), ThemeColor.hex("#D4A764").withAlpha(0.42))), labelColor = ThemeColor.hex("#19141D").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CA9F5F").withAlpha(0.42), ThemeColor.hex("#C1985B").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#F5E7D2").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 8.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_vwe_", heightFraction = 0.40, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.13),
            effects = ThemeEffects.NONE,
        )
    }
    val zenGarden: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.zen-garden",
            name = "Zen Garden",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#CED2A2"), ThemeColor.hex("#C4C798"), ThemeColor.hex("#BCBF90"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_zen_garden", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#A49A7A").withAlpha(0.16), ThemeColor.hex("#A49A7A").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D8CAA4"), ThemeColor.hex("#D2C59F"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C9BC98"), ThemeColor.hex("#C2B694"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#221C28").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CEC19C"), ThemeColor.hex("#C8BB98"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#BEB290"), ThemeColor.hex("#B7AB8B"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#221C28").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D8CAA4"), ThemeColor.hex("#D2C59F"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C9BC98"), ThemeColor.hex("#C2B694"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#221C28").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D8CAA4").withAlpha(0.42), ThemeColor.hex("#D2C59F").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CBBE9A").withAlpha(0.42), ThemeColor.hex("#C4B895").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FBF9F5").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 8.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_zg_", heightFraction = 0.40, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.13),
            effects = ThemeEffects.NONE,
        )
    }
    val autumnCozyCottage: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.autumn-cozy-cottage",
            name = "Autumn Cozy Cottage",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#523E39"), ThemeColor.hex("#6E5348"), ThemeColor.hex("#4B3732"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_autumn_cozy_cottage", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#5C290F").withAlpha(0.18), ThemeColor.hex("#5C290F").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#3E1909"), ThemeColor.hex("#614235"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#755A4F"), ThemeColor.hex("#856D62"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#411C0C").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#614235"), ThemeColor.hex("#755A4F"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#856D62"), ThemeColor.hex("#927C73"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#412C23").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#3E1909"), ThemeColor.hex("#614235"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#755A4F"), ThemeColor.hex("#856D62"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#411C0C").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#3E1909").withAlpha(0.50), ThemeColor.hex("#614235").withAlpha(0.50))), labelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#6E5246").withAlpha(0.50), ThemeColor.hex("#7F665B").withAlpha(0.50))), border = ThemeBorder(ThemeColor.hex("#C7BCB8").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 11.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_acc_", heightFraction = 0.52, bottomInsetFraction = 0.10, opacity = 0.90, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
    val cozyCottagecoreStudio: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.cozy-cottagecore-studio",
            name = "Cozy Cottagecore Studio",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#583C24"), ThemeColor.hex("#695729"), ThemeColor.hex("#52361D"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_cozy_cottagecore_studio", scalesToFill = true, verticalAnchor = 0.54), scrim = ThemeScrim(ThemeColor.hex("#A6875E").withAlpha(0.18), ThemeColor.hex("#A6875E").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#ECC288"), ThemeColor.hex("#E3BA82"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#DBB47E"), ThemeColor.hex("#D1AC78"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#A5875F").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E1B981"), ThemeColor.hex("#D7B17C"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CFAA77"), ThemeColor.hex("#C4A170"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#9D815A").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E7C38F"), ThemeColor.hex("#DEBC8A"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D7B585"), ThemeColor.hex("#CDAD7F"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#A18864").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 9.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#ECC288").withAlpha(0.42), ThemeColor.hex("#E3BA82").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#DDB67F").withAlpha(0.42), ThemeColor.hex("#D3AD79").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FCF7EF").withAlpha(0.32), 1.35), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.22, 3.60, 2.60), cornerRadiusOverrideDp = 11.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_ccs_", heightFraction = 0.52, bottomInsetFraction = 0.10, opacity = 0.90, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
    val enchantedGardenCafe: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.enchanted-garden-cafe",
            name = "Enchanted Garden Cafe",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#EBC7B8"), ThemeColor.hex("#E0BCAD"), ThemeColor.hex("#D8B4A5"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_enchanted_garden_cafe", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#BC9178").withAlpha(0.18), ThemeColor.hex("#BC9178").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FBC9AA"), ThemeColor.hex("#F1C0A3"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#EBBC9F"), ThemeColor.hex("#DFB297"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#AF8C77").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F1C0A3"), ThemeColor.hex("#E5B79B"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#DFB297"), ThemeColor.hex("#D3A88F"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#A88672").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FBC9AA"), ThemeColor.hex("#F1C0A3"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#EBBC9F"), ThemeColor.hex("#DFB297"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#AF8C77").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FBC9AA").withAlpha(0.42), ThemeColor.hex("#F1C0A3").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#EDBDA0").withAlpha(0.42), ThemeColor.hex("#E1B499").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FFFCFB").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 20.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_egf_", heightFraction = 0.50, bottomInsetFraction = 0.10, opacity = 0.90, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
    val enchantedWitchyNight: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.enchanted-witchy-night",
            name = "Enchanted Witchy Night",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#454145"), ThemeColor.hex("#605759"), ThemeColor.hex("#3E3B3E"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_enchanted_witchy_night", scalesToFill = true, verticalAnchor = 0.52), scrim = ThemeScrim(ThemeColor.hex("#31222F").withAlpha(0.20), ThemeColor.hex("#31222F").withAlpha(0.06))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#190E19"), ThemeColor.hex("#382E38"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#615961"), ThemeColor.hex("#6B636A"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D9D7D9").withAlpha(0.85), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#BFBCBF").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#C7C4C7").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#494049"), ThemeColor.hex("#564E56"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#736C73"), ThemeColor.hex("#7B747B"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#E0DEE0").withAlpha(0.85), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#C7C4C7").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#CECCCE").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#190E19"), ThemeColor.hex("#382E38"))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#615961"), ThemeColor.hex("#6B636A"))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D9D7D9").withAlpha(0.85), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#BFBCBF").withAlpha(0.28), cornerRadiusOverrideDp = 12.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#C7C4C7").withAlpha(0.62), bevelWidth = 1.00, bevelFalloff = 0.12, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.36, innerShadowRadius = 3.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#190E19").withAlpha(0.50), ThemeColor.hex("#382E38").withAlpha(0.50))), labelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#595059").withAlpha(0.50), ThemeColor.hex("#635B63").withAlpha(0.50))), border = ThemeBorder(ThemeColor.hex("#BFBCBF").withAlpha(0.60), 1.00), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.32, 2.60, 1.60), topHighlight = ThemeColor.hex("#BFBCBF").withAlpha(0.28), cornerRadiusOverrideDp = 14.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_ewn_", heightFraction = 0.44, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val kawaiiStrawberryDream: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.kawaii-strawberry-dream",
            name = "Kawaii Strawberry Dream",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#F6C2C2"), ThemeColor.hex("#EBB7B7"), ThemeColor.hex("#E3AFAF"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_kawaii_strawberry_dream", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#C2A7A7").withAlpha(0.18), ThemeColor.hex("#C2A7A7").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FBDAD9"), ThemeColor.hex("#F2D2D2"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#EDCECE"), ThemeColor.hex("#E3C5C5"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#AF9898").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F2D2D2"), ThemeColor.hex("#E8C9C9"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E3C5C5"), ThemeColor.hex("#D9BCBC"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#A99392").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FCD9D9"), ThemeColor.hex("#F3D1D2"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#EECDCD"), ThemeColor.hex("#E4C5C5"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#B09898").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FBDAD9").withAlpha(0.42), ThemeColor.hex("#F2D2D2").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#EECFCF").withAlpha(0.42), ThemeColor.hex("#E5C7C6").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FFFCFC").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 20.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_ksd_", heightFraction = 0.50, bottomInsetFraction = 0.10, opacity = 0.90, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
    val lavenderParisNight: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.lavender-paris-night",
            name = "Lavender Paris Night",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#553663"), ThemeColor.hex("#6C4B8A"), ThemeColor.hex("#4F2F5D"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_lavender_paris_night", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#82608B").withAlpha(0.46), ThemeColor.hex("#82608B").withAlpha(0.34))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CBAAD0").withAlpha(0.73), ThemeColor.hex("#C1A1C6").withAlpha(0.73))), labelColor = ThemeColor.hex("#120F16"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B89ABD").withAlpha(0.85), ThemeColor.hex("#AD90B1").withAlpha(0.85))), pressedLabelColor = ThemeColor.hex("#120F16"), border = ThemeBorder(ThemeColor.hex("#EFE5F1").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F8F3F9").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#BF9FC4").withAlpha(0.79), ThemeColor.hex("#B496B8").withAlpha(0.79))), labelColor = ThemeColor.hex("#120F16"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#AA8EAE").withAlpha(0.91), ThemeColor.hex("#9D83A1").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#120F16"), border = ThemeBorder(ThemeColor.hex("#E8DDEA").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F2EBF3").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CBAAD0").withAlpha(0.79), ThemeColor.hex("#C1A1C6").withAlpha(0.79))), labelColor = ThemeColor.hex("#120F16"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B89ABD").withAlpha(0.91), ThemeColor.hex("#AD90B1").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#120F16"), border = ThemeBorder(ThemeColor.hex("#EFE5F1").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F8F3F9").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#CBAAD0").withAlpha(0.42), ThemeColor.hex("#C1A1C6").withAlpha(0.42))), labelColor = ThemeColor.hex("#120F16").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#BB9CBF").withAlpha(0.42), ThemeColor.hex("#AF92B3").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#EFE5F1").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.50), cornerRadiusOverrideDp = 15.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_lpn_", heightFraction = 0.46, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val matchaGarden: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.matcha-garden",
            name = "Matcha Garden",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#D4D0A4"), ThemeColor.hex("#CAC69A"), ThemeColor.hex("#C2BD92"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_matcha_garden", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#A09966").withAlpha(0.16), ThemeColor.hex("#A09966").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D1CB9A"), ThemeColor.hex("#CBC695"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C2BD8F"), ThemeColor.hex("#BBB68A"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#221C28").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#C7C292"), ThemeColor.hex("#C1BC8E"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#B7B287"), ThemeColor.hex("#B0AB82"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#221C28").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D2CB94"), ThemeColor.hex("#CCC690"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C3BC89"), ThemeColor.hex("#BDB685"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#221C28").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 6.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D1CB9A").withAlpha(0.42), ThemeColor.hex("#CBC695").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C3BE90").withAlpha(0.42), ThemeColor.hex("#BDB88B").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#F9F8F1").withAlpha(0.80), 1.70), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.00, 0.00, 0.00), cornerRadiusOverrideDp = 8.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mg_", heightFraction = 0.40, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.13),
            effects = ThemeEffects.NONE,
        )
    }
    val mermaidDreamscape: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.mermaid-dreamscape",
            name = "Mermaid Dreamscape",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#E6C1F8"), ThemeColor.hex("#DBB7EE"), ThemeColor.hex("#D3AEE6"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_mermaid_dreamscape", scalesToFill = true, verticalAnchor = 0.3), scrim = ThemeScrim(ThemeColor.hex("#A68AAE").withAlpha(0.18), ThemeColor.hex("#A68AAE").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E8C5D0"), ThemeColor.hex("#D7B5D0"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D8B8C2"), ThemeColor.hex("#C6A7BF"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FDFBFB").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#DDBDCC"), ThemeColor.hex("#CBADBB"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CCAFBD"), ThemeColor.hex("#B89DAA"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#F9F4F6").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E7C6D6"), ThemeColor.hex("#D6B7C6"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D8B9C7"), ThemeColor.hex("#C5A8B6"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#FDFBFC").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E8C5D0").withAlpha(0.42), ThemeColor.hex("#D7B5D0").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#DAB9C3").withAlpha(0.42), ThemeColor.hex("#C8A8C1").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FDFBFB").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 16.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mds_", heightFraction = 0.48, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val midnightCafe: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.midnight-cafe",
            name = "Midnight Cafe",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#493E54"), ThemeColor.hex("#655175"), ThemeColor.hex("#43374E"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_midnight_cafe", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#3F2644").withAlpha(0.46), ThemeColor.hex("#3F2644").withAlpha(0.34))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#28172B").withAlpha(0.73), ThemeColor.hex("#504252").withAlpha(0.73))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#665B68").withAlpha(0.85), ThemeColor.hex("#776D79").withAlpha(0.85))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#C9C4C9").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#C1BCC2").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#C9C4C9").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#504252").withAlpha(0.79), ThemeColor.hex("#665B68").withAlpha(0.79))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#776D79").withAlpha(0.91), ThemeColor.hex("#857C87").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#D0CCD0").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#C9C4C9").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#D0CCD0").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#27172C").withAlpha(0.79), ThemeColor.hex("#4F4253").withAlpha(0.79))), labelColor = ThemeColor.hex("#FFFFFF"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#665B69").withAlpha(0.91), ThemeColor.hex("#776D7A").withAlpha(0.91))), pressedLabelColor = ThemeColor.hex("#FFFFFF"), border = ThemeBorder(ThemeColor.hex("#C8C4CA").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#C1BCC2").withAlpha(0.50), cornerRadiusOverrideDp = 13.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#C8C4CA").withAlpha(0.74), bevelWidth = 1.10, bevelFalloff = 0.40, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.18, innerShadowRadius = 2.60)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#28172B").withAlpha(0.50), ThemeColor.hex("#504252").withAlpha(0.50))), labelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#5E5260").withAlpha(0.50), ThemeColor.hex("#716673").withAlpha(0.50))), border = ThemeBorder(ThemeColor.hex("#C1BCC2").withAlpha(0.50), 1.05), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.17, 1.90, 1.10), topHighlight = ThemeColor.hex("#C1BCC2").withAlpha(0.50), cornerRadiusOverrideDp = 15.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mc_", heightFraction = 0.46, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val moonlitBeachEscape: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.moonlit-beach-escape",
            name = "Moonlit Beach Escape",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#4B347F"), ThemeColor.hex("#74419E"), ThemeColor.hex("#442D79"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_moonlit_beach_escape", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#94668A").withAlpha(0.18), ThemeColor.hex("#94668A").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E5AAA3"), ThemeColor.hex("#CE90A7"))), labelColor = ThemeColor.hex("#000000"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D19B94"), ThemeColor.hex("#B57F92"))), pressedLabelColor = ThemeColor.hex("#000000"), border = ThemeBorder(ThemeColor.hex("#F8E7E6").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FCF6F5").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#D69B9E"), ThemeColor.hex("#BB888B"))), labelColor = ThemeColor.hex("#000000"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#BE8A8D"), ThemeColor.hex("#9F7376"))), pressedLabelColor = ThemeColor.hex("#000000"), border = ThemeBorder(ThemeColor.hex("#F1DCDD").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#F7EBEB").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E3A5A8"), ThemeColor.hex("#CC9397"))), labelColor = ThemeColor.hex("#000000"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#CE9599"), ThemeColor.hex("#B38184"))), pressedLabelColor = ThemeColor.hex("#000000"), border = ThemeBorder(ThemeColor.hex("#F7E4E5").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FBF3F3").withAlpha(0.60), bevelWidth = 0.80, bevelFalloff = 0.18, innerShadowColor = ThemeColor.hex("#0A080F"), innerShadowOpacity = 0.12, innerShadowRadius = 2.00)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#E5AAA3").withAlpha(0.42), ThemeColor.hex("#CE90A7").withAlpha(0.42))), labelColor = ThemeColor.hex("#000000").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D39D96").withAlpha(0.42), ThemeColor.hex("#B88195").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#F8E7E6").withAlpha(0.42), 0.95), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.15, 2.20, 1.30), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.46), cornerRadiusOverrideDp = 16.0)),
            typography = ThemeTypography(weightRawValue = 0.3, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_mbe_", heightFraction = 0.48, bottomInsetFraction = 0.09, opacity = 0.90, labelLiftFraction = 0.14),
            effects = ThemeEffects.NONE,
        )
    }
    val starlitDreamCafe: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.starlit-dream-cafe",
            name = "Starlit Dream Cafe",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#F5C0D3"), ThemeColor.hex("#EBB5C8"), ThemeColor.hex("#E2ADC0"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_starlit_dream_cafe", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#B38489").withAlpha(0.18), ThemeColor.hex("#B38489").withAlpha(0.05))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F7BEBC"), ThemeColor.hex("#EBB5B3"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E5B0AF"), ThemeColor.hex("#D9A7A5"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#AC8483").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#EBB5B3"), ThemeColor.hex("#DFACAA"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D9A7A5"), ThemeColor.hex("#CB9C9B"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#A47E7D").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFEFE").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F7BEBC"), ThemeColor.hex("#EBB5B3"))), labelColor = ThemeColor.hex("#221C28"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E5B0AF"), ThemeColor.hex("#D9A7A5"))), pressedLabelColor = ThemeColor.hex("#221C28"), border = ThemeBorder(ThemeColor.hex("#AC8483").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 19.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.00, bevelFalloff = 0.50, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.34, innerShadowRadius = 3.20)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F7BEBC").withAlpha(0.42), ThemeColor.hex("#EBB5B3").withAlpha(0.42))), labelColor = ThemeColor.hex("#221C28").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E7B2B0").withAlpha(0.42), ThemeColor.hex("#DBA8A7").withAlpha(0.42))), border = ThemeBorder(ThemeColor.hex("#FEF8F8").withAlpha(0.40), 1.15), shadow = ThemeShadow(ThemeColor.hex("#0F0A17"), 0.30, 4.20, 3.00), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.62), cornerRadiusOverrideDp = 20.0)),
            typography = ThemeTypography(weightRawValue = 0.36, sizeMultiplier = 1.0),
            keyArt = KeyArtSet(assetPrefix = "keyart_sdc_", heightFraction = 0.50, bottomInsetFraction = 0.10, opacity = 0.90, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
}
