package com.mochi.keyboard.ime.render

/** Batch 8.0 built-in themes, machine-ported from iOS's
 * `BuiltInThemes+Batch8.swift` (same source of truth, same token values, same art). */
object BuiltInThemesBatch8 {
    val all: List<MochiKeyboardTheme> get() = listOf(kawaiiBobaTea, pastelPinkSky, sakuraTrain)

    val kawaiiBobaTea: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.kawaii-boba-tea",
            name = "Kawaii Boba Tea",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#F9E1B9"), ThemeColor.hex("#FBEAC9"), ThemeColor.hex("#FAE3BB"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_kawaii_boba_tea", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#FFF6E6").withAlpha(0.10), ThemeColor.hex("#FFF6E6").withAlpha(0.04))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FFFAF1"), ThemeColor.hex("#F8EBD6"))), labelColor = ThemeColor.hex("#5A3820"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#F0DEC2"), ThemeColor.hex("#E6D0AE"))), border = ThemeBorder(ThemeColor.hex("#C9A27A").withAlpha(0.55), 1.0), shadow = ThemeShadow(ThemeColor.hex("#6B4424"), 0.22, 3.0, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.40), cornerRadiusOverrideDp = 12.0), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F3E1C6"), ThemeColor.hex("#EAD2AE"))), labelColor = ThemeColor.hex("#5A3820"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E2CCA8"), ThemeColor.hex("#D8BC94"))), border = ThemeBorder(ThemeColor.hex("#C09670").withAlpha(0.55), 1.0), shadow = ThemeShadow(ThemeColor.hex("#6B4424"), 0.22, 3.0, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.35), cornerRadiusOverrideDp = 12.0), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F0C99E"), ThemeColor.hex("#E2AE7C"))), labelColor = ThemeColor.hex("#3E2210"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E0B488"), ThemeColor.hex("#D29C68"))), border = ThemeBorder(ThemeColor.hex("#B07A4C").withAlpha(0.55), 1.0), shadow = ThemeShadow(ThemeColor.hex("#6B4424"), 0.24, 3.0, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.35), cornerRadiusOverrideDp = 12.0), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FFF6EA").withAlpha(0.55), ThemeColor.hex("#F4E4CC").withAlpha(0.55))), labelColor = ThemeColor.hex("#000000").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C9A27A").withAlpha(0.72), ThemeColor.hex("#C9A27A").withAlpha(0.72))), border = ThemeBorder(ThemeColor.hex("#C9A27A").withAlpha(0.80), 1.0), shadow = ThemeShadow(ThemeColor.hex("#6B4424"), 0.20, 3.0, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.35), cornerRadiusOverrideDp = 13.0)),
            typography = ThemeTypography(weightRawValue = 0.34, sizeMultiplier = 1.0),
            chrome = ThemeChrome(inkColor = ThemeColor.hex("#4A2E18"), mutedInkColor = ThemeColor.hex("#4A2E18").withAlpha(0.60), panelFill = ThemeFill(ThemeColor.hex("#FFF6E8").withAlpha(0.60)), highlightFill = ThemeFill(ThemeColor.hex("#6B4424").withAlpha(0.18))),
            keyArt = KeyArtSet(assetPrefix = "keyart_kb_", heightFraction = 0.54, bottomInsetFraction = 0.07, opacity = 1.0, labelLiftFraction = 0.15),
            effects = ThemeEffects.NONE,
        )
    }
    val pastelPinkSky: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.pastel-pink-sky",
            name = "Pastel Pink Sky",
            authorName = "Mochi",
            appearance = ThemeAppearance.LIGHT,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#E792A8"), ThemeColor.hex("#FAA7B3"), ThemeColor.hex("#FAA7AC"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_pastel_pink_sky", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#FFFFFF").withAlpha(0.10), ThemeColor.hex("#FFE6EE").withAlpha(0.04))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FFF8FB").withAlpha(0.86), ThemeColor.hex("#FFE4EE").withAlpha(0.86))), labelColor = ThemeColor.hex("#6A2644"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#F8D6E4").withAlpha(0.92), ThemeColor.hex("#F2C4D6").withAlpha(0.92))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.80), 1.0), shadow = ThemeShadow(ThemeColor.hex("#8A3A5A"), 0.24, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.65), cornerRadiusOverrideDp = 16.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.0, bevelFalloff = 0.5, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.45, innerShadowRadius = 3.5)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FDE0EB").withAlpha(0.88), ThemeColor.hex("#F8C8DA").withAlpha(0.88))), labelColor = ThemeColor.hex("#6A2644"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#F2C8D8").withAlpha(0.94), ThemeColor.hex("#EAB2C8").withAlpha(0.94))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.75), 1.0), shadow = ThemeShadow(ThemeColor.hex("#8A3A5A"), 0.24, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.60), cornerRadiusOverrideDp = 16.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.0, bevelFalloff = 0.5, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.40, innerShadowRadius = 3.5)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FFE6D6").withAlpha(0.92), ThemeColor.hex("#FFC4A4").withAlpha(0.92))), labelColor = ThemeColor.hex("#5A2418"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#F8D0B8").withAlpha(0.96), ThemeColor.hex("#F4B08C").withAlpha(0.96))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.80), 1.0), shadow = ThemeShadow(ThemeColor.hex("#8A3A3A"), 0.24, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.65), cornerRadiusOverrideDp = 16.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.00), bevelWidth = 0.0, bevelFalloff = 0.5, innerShadowColor = ThemeColor.hex("#FFFFFF"), innerShadowOpacity = 0.45, innerShadowRadius = 3.5)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FFF2F6").withAlpha(0.45), ThemeColor.hex("#FFDCE8").withAlpha(0.45))), labelColor = ThemeColor.hex("#000000").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#C06080").withAlpha(0.72), ThemeColor.hex("#C06080").withAlpha(0.72))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.80), 1.0), shadow = ThemeShadow(ThemeColor.hex("#8A3A5A"), 0.22, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.35), cornerRadiusOverrideDp = 17.0)),
            typography = ThemeTypography(weightRawValue = 0.32, sizeMultiplier = 1.0),
            chrome = ThemeChrome(inkColor = ThemeColor.hex("#5A2038"), mutedInkColor = ThemeColor.hex("#5A2038").withAlpha(0.60), panelFill = ThemeFill(ThemeColor.hex("#FFF0F5").withAlpha(0.55)), highlightFill = ThemeFill(ThemeColor.hex("#8A3A5A").withAlpha(0.18))),
            keyArt = KeyArtSet(assetPrefix = "keyart_pps_", heightFraction = 0.54, bottomInsetFraction = 0.07, opacity = 1.0, labelLiftFraction = 0.15),
            effects = ThemeEffects(isEnabled = true, birthRate = 3.0, tint = ThemeColor.hex("#FFE0B0")),
        )
    }
    val sakuraTrain: MochiKeyboardTheme by lazy {
        MochiKeyboardTheme(
            id = "mochi.sakura-train",
            name = "Sakura Train",
            authorName = "Mochi",
            appearance = ThemeAppearance.DARK,
            surface = ThemeSurface(baseFill = ThemeFill(listOf(ThemeColor.hex("#8A53C1"), ThemeColor.hex("#B46FD9"), ThemeColor.hex("#BF72D9"))), backgroundImage = ThemeBackgroundImage(bundledName = "themebg_sakura_train", scalesToFill = true, verticalAnchor = 0.5), scrim = ThemeScrim(ThemeColor.hex("#3A1E6A").withAlpha(0.14), ThemeColor.hex("#3A1E6A").withAlpha(0.06))),
            keyStyles = mapOf(KeyRole.INPUT to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FDF8FF").withAlpha(0.92), ThemeColor.hex("#EDDFFB").withAlpha(0.92))), labelColor = ThemeColor.hex("#35195A"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#E4D2F6").withAlpha(0.98), ThemeColor.hex("#D3BDEE").withAlpha(0.98))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.72), 1.0), shadow = ThemeShadow(ThemeColor.hex("#24104A"), 0.30, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.55), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.85), bevelWidth = 1.2, bevelFalloff = 0.5, innerShadowColor = ThemeColor.hex("#6A40A0"), innerShadowOpacity = 0.30, innerShadowRadius = 3.0)), KeyRole.SYSTEM to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#EADAFA").withAlpha(0.92), ThemeColor.hex("#D8C2F2").withAlpha(0.92))), labelColor = ThemeColor.hex("#35195A"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#D6C0EE").withAlpha(0.98), ThemeColor.hex("#C4AAE6").withAlpha(0.98))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.72), 1.0), shadow = ThemeShadow(ThemeColor.hex("#24104A"), 0.30, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.48), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.85), bevelWidth = 1.2, bevelFalloff = 0.5, innerShadowColor = ThemeColor.hex("#6A40A0"), innerShadowOpacity = 0.30, innerShadowRadius = 3.0)), KeyRole.ACTION to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#FFE4F2").withAlpha(0.94), ThemeColor.hex("#F8BCDA").withAlpha(0.94))), labelColor = ThemeColor.hex("#4A1840"), pressedFill = ThemeFill(listOf(ThemeColor.hex("#F2CCE0").withAlpha(0.98), ThemeColor.hex("#EAA6C8").withAlpha(0.98))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.72), 1.0), shadow = ThemeShadow(ThemeColor.hex("#2E0A2A"), 0.30, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.55), cornerRadiusOverrideDp = 14.0, glass = KeyGlass(bevelColor = ThemeColor.hex("#FFFFFF").withAlpha(0.85), bevelWidth = 1.2, bevelFalloff = 0.5, innerShadowColor = ThemeColor.hex("#8A3070"), innerShadowOpacity = 0.30, innerShadowRadius = 3.0)), KeyRole.SPACE to KeyStyle(fill = ThemeFill(listOf(ThemeColor.hex("#F8EEFF").withAlpha(0.45), ThemeColor.hex("#E4D0F8").withAlpha(0.45))), labelColor = ThemeColor.hex("#000000").withAlpha(0.00), pressedFill = ThemeFill(listOf(ThemeColor.hex("#3A1E6A").withAlpha(0.72), ThemeColor.hex("#3A1E6A").withAlpha(0.72))), border = ThemeBorder(ThemeColor.hex("#FFFFFF").withAlpha(0.80), 1.0), shadow = ThemeShadow(ThemeColor.hex("#24104A"), 0.28, 3.5, 2.0), topHighlight = ThemeColor.hex("#FFFFFF").withAlpha(0.35), cornerRadiusOverrideDp = 15.0)),
            typography = ThemeTypography(weightRawValue = 0.32, sizeMultiplier = 1.0),
            chrome = ThemeChrome(inkColor = ThemeColor.hex("#FFFFFF"), mutedInkColor = ThemeColor.hex("#FFFFFF").withAlpha(0.60), panelFill = ThemeFill(ThemeColor.hex("#2A1450").withAlpha(0.55)), highlightFill = ThemeFill(ThemeColor.hex("#FFFFFF").withAlpha(0.18))),
            keyArt = KeyArtSet(assetPrefix = "keyart_st_", heightFraction = 0.54, bottomInsetFraction = 0.07, opacity = 0.98, labelLiftFraction = 0.15),
            effects = ThemeEffects(isEnabled = true, birthRate = 4.0, tint = ThemeColor.hex("#FFC6E6")),
        )
    }
}
