import Foundation

/// What each theme is *about* — the pill it belongs under, the hashtags on its card, the words it
/// can be found by, and the one line that describes it.
///
/// Every entry is derived from the theme's own material: the words in its name, mapped through a
/// subject table (`sakura` → cherry blossom/spring, `atelier` → studio/art, `arcade` → games/retro),
/// plus the **measured** dominant colours and overall tone of its own background plate — so "pink",
/// "dark" or "pastel" in a search query match what the theme actually looks like rather than what
/// someone guessed it looks like. Generated by `scratchpad/gen_semantics.py`; regenerate it rather
/// than hand-editing a row, or the next batch of themes will silently disagree with this one.
///
/// This replaces the placeholder tags the batch generators wrote (`["other", "abyssal", "neon"]`),
/// which put the literal word "other" on a card and made the category pills close to meaningless.
enum ThemeSemantics {
    struct Entry {
        let category: ThemeCategory
        /// The hashtags shown on the theme's card.
        let tags: [String]
        /// Everything this theme can be found by — subject, mood, colour and tone words.
        let keywords: [String]
        /// One line of description, used on Community cards and Theme Detail.
        let blurb: String
    }

    static let byID: [String: Entry] = [
        "mochi.abyssal-neon-haven": Entry(
            category: .other, tags: ["dark", "glow", "teal"],
            keywords: ["deep sea", "dark", "glow", "neon", "nightlife", "calm", "retreat", "teal", "blue", "pastel", "abyssal", "haven"],
            blurb: "Pastel teal keys with dark and glow details."),
        "mochi.adventure-awaits": Entry(
            category: .other, tags: ["adventure", "journey", "cream"],
            keywords: ["adventure", "journey", "explore", "cream", "green", "pastel", "awaits"],
            blurb: "Pastel cream keys with adventure and journey details."),
        "mochi.aether-garden": Entry(
            category: .nature, tags: ["ethereal", "magic", "orange"],
            keywords: ["ethereal", "magic", "floating", "garden", "flowers", "plants", "orange", "brown", "bright", "aether"],
            blurb: "Bright orange keys with ethereal and magic details."),
        "mochi.alien-moonlift": Entry(
            category: .space, tags: ["space", "alien", "blue"],
            keywords: ["space", "alien", "ufo", "moon", "blue", "dark", "moonlift"],
            blurb: "Dark blue keys with space and alien details."),
        "mochi.alien-playtopia": Entry(
            category: .space, tags: ["space", "alien", "blue"],
            keywords: ["space", "alien", "ufo", "playful", "fun", "toys", "blue", "purple", "pastel", "playtopia"],
            blurb: "Pastel blue keys with space and alien details."),
        "mochi.astral-gearworks": Entry(
            category: .space, tags: ["space", "astral", "dark"],
            keywords: ["space", "astral", "stars", "gears", "steampunk", "machines", "dark", "gearworks"],
            blurb: "Dark keys with space and astral details."),
        "mochi.aurora-frontier": Entry(
            category: .space, tags: ["aurora", "glow", "blue"],
            keywords: ["aurora", "northern lights", "glow", "wilderness", "mountains", "blue", "dark", "frontier"],
            blurb: "Dark blue keys with aurora and glow details."),
        "mochi.aurora-moonlit-observatory": Entry(
            category: .space, tags: ["aurora", "glow", "blue"],
            keywords: ["aurora", "northern lights", "glow", "moon", "night", "moonlight", "space", "stars", "telescope", "blue", "dark", "moonlit"],
            blurb: "Dark blue keys with aurora and glow details."),
        "mochi.aurora-timber-lodge": Entry(
            category: .space, tags: ["aurora", "glow", "brown"],
            keywords: ["aurora", "northern lights", "glow", "wood", "forest", "cabin", "lodge", "warm", "brown", "orange", "bright", "timber"],
            blurb: "Bright brown keys with aurora and glow details."),
        "mochi.aurora-winter-wonderland": Entry(
            category: .space, tags: ["aurora", "glow", "blue"],
            keywords: ["aurora", "northern lights", "glow", "winter", "snow", "cold", "magic", "blue", "purple", "pastel", "wonderland"],
            blurb: "Pastel blue keys with aurora and glow details."),
        "mochi.autumn-cozy-cottage": Entry(
            category: .cozy, tags: ["cozy", "warm", "brown"],
            keywords: ["cozy", "warm", "comfy", "cottage", "cottagecore", "home", "brown", "dark", "autumn"],
            blurb: "Dark brown keys with cozy and warm details."),
        "mochi.azure-summer-escape": Entry(
            category: .elegant, tags: ["blue", "summer", "blue"],
            keywords: ["blue", "summer", "sea", "warm", "holiday", "cream", "pastel", "azure", "escape"],
            blurb: "Pastel blue keys with blue and summer details."),
        "mochi.beyond-the-horizon": Entry(
            category: .dreamy, tags: ["horizon", "sky", "dark"],
            keywords: ["horizon", "sky", "journey", "sunset", "dark", "blue", "beyond"],
            blurb: "Dark keys with horizon and sky details."),
        "mochi.bionova-nexus": Entry(
            category: .space, tags: ["futuristic", "tech", "dark"],
            keywords: ["futuristic", "tech", "glow", "dark", "teal", "bionova", "nexus"],
            blurb: "Dark keys with futuristic and tech details."),
        "mochi.blooming-gardenia": Entry(
            category: .nature, tags: ["flowers", "bloom", "cream"],
            keywords: ["flowers", "bloom", "garden", "cream", "brown", "pastel", "blooming", "gardenia"],
            blurb: "Pastel cream keys with flowers and bloom details."),
        "mochi.botanical-cafe": Entry(
            category: .nature, tags: ["plants", "botanical", "cream"],
            keywords: ["plants", "botanical", "leaves", "cafe", "coffee", "warm", "cream", "brown", "bright"],
            blurb: "Bright cream keys with plants and botanical details."),
        "mochi.botanical-workshop": Entry(
            category: .nature, tags: ["plants", "botanical", "cream"],
            keywords: ["plants", "botanical", "leaves", "workshop", "craft", "tools", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with plants and botanical details."),
        "mochi.bubblegum-circuit": Entry(
            category: .cute, tags: ["bubblegum", "candy", "purple"],
            keywords: ["bubblegum", "candy", "sweet", "purple", "magenta", "pastel", "circuit"],
            blurb: "Pastel purple keys with bubblegum and candy details."),
        "mochi.candy-bakery": Entry(
            category: .cute, tags: ["candy", "sweets", "cream"],
            keywords: ["candy", "sweets", "sugar", "bakery", "baking", "cream", "red", "pastel"],
            blurb: "Pastel cream keys with candy and sweets details."),
        "mochi.canvas-and-coffee": Entry(
            category: .cozy, tags: ["art", "painting", "orange"],
            keywords: ["art", "painting", "studio", "coffee", "cafe", "orange", "brown", "bright", "canvas"],
            blurb: "Bright orange keys with art and painting details."),
        "mochi.captured-moments": Entry(
            category: .elegant, tags: ["photography", "memories", "orange"],
            keywords: ["photography", "memories", "camera", "photos", "orange", "brown", "bright", "captured", "moments"],
            blurb: "Bright orange keys with photography and memories details."),
        "mochi.clockwork-horizon": Entry(
            category: .dreamy, tags: ["clockwork", "steampunk", "brown"],
            keywords: ["clockwork", "steampunk", "gears", "horizon", "sky", "sunset", "brown", "dark"],
            blurb: "Dark brown keys with clockwork and steampunk details."),
        "mochi.cosmic-astronaut": Entry(
            category: .space, tags: ["space", "cosmic", "blue"],
            keywords: ["space", "cosmic", "galaxy", "stars", "astronaut", "blue", "pastel"],
            blurb: "Pastel blue keys with space and cosmic details."),
        "mochi.cosmic-daydream-station": Entry(
            category: .space, tags: ["space", "cosmic", "purple"],
            keywords: ["space", "cosmic", "galaxy", "stars", "dreamy", "daydream", "purple", "pastel", "station"],
            blurb: "Pastel purple keys with space and cosmic details."),
        "mochi.cosmic-little-visitors": Entry(
            category: .space, tags: ["space", "cosmic", "purple"],
            keywords: ["space", "cosmic", "galaxy", "stars", "aliens", "cute", "purple", "pastel", "little", "visitors"],
            blurb: "Pastel purple keys with space and cosmic details."),
        "mochi.cosmic-observatory": Entry(
            category: .space, tags: ["space", "cosmic", "purple"],
            keywords: ["space", "cosmic", "galaxy", "stars", "telescope", "purple", "dark", "observatory"],
            blurb: "Dark purple keys with space and cosmic details."),
        "mochi.cozy-cat": Entry(
            category: .cozy, tags: ["cozy", "warm", "pink"],
            keywords: ["cozy", "warm", "comfy", "cat", "kitten", "animal", "pink", "red", "pastel"],
            blurb: "Pastel pink keys with cozy and warm details."),
        "mochi.cozy-cottagecore-studio": Entry(
            category: .cozy, tags: ["cozy", "warm", "orange"],
            keywords: ["cozy", "warm", "comfy", "cottage", "cottagecore", "orange", "brown", "bright", "studio"],
            blurb: "Bright orange keys with cozy and warm details."),
        "mochi.cozy-countryside-farm": Entry(
            category: .cozy, tags: ["cozy", "warm", "cream"],
            keywords: ["cozy", "warm", "comfy", "countryside", "rural", "farm", "cream", "pastel"],
            blurb: "Pastel cream keys with cozy and warm details."),
        "mochi.cozy-garden-cottage": Entry(
            category: .nature, tags: ["cozy", "warm", "cream"],
            keywords: ["cozy", "warm", "comfy", "garden", "flowers", "plants", "cottage", "cottagecore", "home", "cream", "brown", "bright"],
            blurb: "Bright cream keys with cozy and warm details."),
        "mochi.cozy-night-keyboard": Entry(
            category: .cozy, tags: ["cozy", "warm", "pink"],
            keywords: ["cozy", "warm", "comfy", "night", "dark", "pink", "purple", "pastel", "keyboard"],
            blurb: "Pastel pink keys with cozy and warm details."),
        "mochi.cozy-sakura-cafe": Entry(
            category: .cozy, tags: ["cozy", "warm", "purple"],
            keywords: ["cozy", "warm", "comfy", "sakura", "cherry blossom", "spring", "cafe", "coffee", "purple", "magenta", "bright", "café"],
            blurb: "Bright purple keys with cozy and warm details."),
        "mochi.cozy-terrarium": Entry(
            category: .nature, tags: ["cozy", "warm", "cream"],
            keywords: ["cozy", "warm", "comfy", "plants", "glass", "moss", "cream", "brown", "pastel", "terrarium"],
            blurb: "Pastel cream keys with cozy and warm details."),
        "mochi.cozy-yarn-haven": Entry(
            category: .cozy, tags: ["cozy", "warm", "red"],
            keywords: ["cozy", "warm", "comfy", "yarn", "knitting", "craft", "calm", "retreat", "red", "orange", "bright", "haven"],
            blurb: "Bright red keys with cozy and warm details."),
        "mochi.creative-workspace": Entry(
            category: .cozy, tags: ["art", "creative", "cream"],
            keywords: ["art", "creative", "studio", "desk", "workspace", "study", "cream", "orange", "bright"],
            blurb: "Bright cream keys with art and creative details."),
        "mochi.deep-sea-explorer": Entry(
            category: .nature, tags: ["ocean", "sea", "teal"],
            keywords: ["ocean", "sea", "water", "explorer", "adventure", "journey", "teal", "green", "pastel", "deep"],
            blurb: "Pastel teal keys with ocean and sea details."),
        "mochi.dragonlight-valley": Entry(
            category: .nature, tags: ["dragon", "fantasy", "brown"],
            keywords: ["dragon", "fantasy", "brown", "orange", "pastel", "dragonlight", "valley"],
            blurb: "Pastel brown keys with dragon and fantasy details."),
        "mochi.dreams-in-rewind": Entry(
            category: .dreamy, tags: ["dreamy", "dreams", "dark"],
            keywords: ["dreamy", "dreams", "retro", "tape", "nostalgia", "dark", "purple", "rewind"],
            blurb: "Dark keys with dreamy and dreams details."),
        "mochi.dreamscape-portal": Entry(
            category: .dreamy, tags: ["dreamy", "surreal", "purple"],
            keywords: ["dreamy", "surreal", "portal", "magic", "purple", "magenta", "pastel", "dreamscape"],
            blurb: "Pastel purple keys with dreamy and surreal details."),
        "mochi.dreamy-castle": Entry(
            category: .dreamy, tags: ["dreamy", "soft", "magenta"],
            keywords: ["dreamy", "soft", "castle", "fairytale", "fantasy", "magenta", "purple", "pastel"],
            blurb: "Pastel magenta keys with dreamy and soft details."),
        "mochi.dreamy-control-room": Entry(
            category: .dreamy, tags: ["dreamy", "soft", "purple"],
            keywords: ["dreamy", "soft", "control room", "retro tech", "room", "interior", "purple", "magenta", "pastel", "control"],
            blurb: "Pastel purple keys with dreamy and soft details."),
        "mochi.dreamy-garden": Entry(
            category: .nature, tags: ["dreamy", "soft", "cream"],
            keywords: ["dreamy", "soft", "garden", "flowers", "plants", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with dreamy and soft details."),
        "mochi.egypt-through-time": Entry(
            category: .elegant, tags: ["egypt", "pyramids", "dark"],
            keywords: ["egypt", "pyramids", "ancient", "dark", "brown", "through", "time"],
            blurb: "Dark keys with egypt and pyramids details."),
        "mochi.emberwatch-observatory": Entry(
            category: .space, tags: ["ember", "warm", "dark"],
            keywords: ["ember", "warm", "observatory", "space", "stars", "telescope", "dark", "red", "emberwatch"],
            blurb: "Dark keys with ember and warm details."),
        "mochi.enchanted-garden-cafe": Entry(
            category: .nature, tags: ["enchanted", "magic", "orange"],
            keywords: ["enchanted", "magic", "fairytale", "garden", "flowers", "plants", "cafe", "coffee", "warm", "orange", "cream", "pastel"],
            blurb: "Pastel orange keys with enchanted and magic details."),
        "mochi.enchanted-glass-garden": Entry(
            category: .nature, tags: ["enchanted", "magic", "cream"],
            keywords: ["enchanted", "magic", "fairytale", "glass", "shiny", "garden", "flowers", "plants", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with enchanted and magic details."),
        "mochi.enchanted-midnight-library": Entry(
            category: .cozy, tags: ["enchanted", "magic", "purple"],
            keywords: ["enchanted", "magic", "fairytale", "midnight", "night", "dark", "books", "library", "reading", "purple"],
            blurb: "Dark purple keys with enchanted and magic details."),
        "mochi.enchanted-witchy-night": Entry(
            category: .dreamy, tags: ["enchanted", "magic", "dark"],
            keywords: ["enchanted", "magic", "fairytale", "witch", "spooky", "night", "dark", "witchy"],
            blurb: "Dark keys with enchanted and magic details."),
        "mochi.fantasy-castle-night": Entry(
            category: .dreamy, tags: ["fantasy", "fairytale", "purple"],
            keywords: ["fantasy", "fairytale", "magic", "castle", "night", "dark", "purple", "blue", "bright"],
            blurb: "Bright purple keys with fantasy and fairytale details."),
        "mochi.firework-dream-festival": Entry(
            category: .cute, tags: ["fireworks", "festival", "purple"],
            keywords: ["fireworks", "festival", "celebration", "dreamy", "dreams", "soft", "lights", "purple", "pink", "bright", "firework", "dream"],
            blurb: "Bright purple keys with fireworks and festival details."),
        "mochi.floating-dreamscape": Entry(
            category: .dreamy, tags: ["floating", "clouds", "purple"],
            keywords: ["floating", "clouds", "sky", "dreamy", "surreal", "purple", "blue", "pastel", "dreamscape"],
            blurb: "Pastel purple keys with floating and clouds details."),
        "mochi.forgotten-ruins": Entry(
            category: .other, tags: ["ancient", "ruins", "dark"],
            keywords: ["ancient", "ruins", "mystery", "adventure", "dark", "brown", "forgotten"],
            blurb: "Dark keys with ancient and ruins details."),
        "mochi.frosted-crystal-cavern": Entry(
            category: .nature, tags: ["ice", "frost", "blue"],
            keywords: ["ice", "frost", "winter", "crystal", "gems", "cave", "blue", "bright", "frosted", "cavern"],
            blurb: "Bright blue keys with ice and frost details."),
        "mochi.galaxy-mart": Entry(
            category: .space, tags: ["space", "galaxy", "dark"],
            keywords: ["space", "galaxy", "stars", "shop", "store", "snacks", "dark", "purple", "mart"],
            blurb: "Dark keys with space and galaxy details."),
        "mochi.glitch-garden": Entry(
            category: .nature, tags: ["glitch", "digital", "blue"],
            keywords: ["glitch", "digital", "neon", "garden", "flowers", "plants", "blue", "purple", "dark"],
            blurb: "Dark blue keys with glitch and digital details."),
        "mochi.golden-midway": Entry(
            category: .cute, tags: ["gold", "warm", "brown"],
            keywords: ["gold", "warm", "glow", "carnival", "fair", "lights", "brown", "orange", "bright", "golden", "midway"],
            blurb: "Bright brown keys with gold and warm details."),
        "mochi.holographic-daydream": Entry(
            category: .dreamy, tags: ["holographic", "iridescent", "purple"],
            keywords: ["holographic", "iridescent", "shiny", "dreamy", "daydream", "purple", "blue", "pastel"],
            blurb: "Pastel purple keys with holographic and iridescent details."),
        "mochi.iron-and-ember-loft": Entry(
            category: .cozy, tags: ["industrial", "metal", "dark"],
            keywords: ["industrial", "metal", "loft", "fire", "ember", "warm", "room", "home", "dark", "brown", "iron"],
            blurb: "Dark keys with industrial and metal details."),
        "mochi.japanese-zen": Entry(
            category: .nature, tags: ["japan", "japanese", "cream"],
            keywords: ["japan", "japanese", "zen", "calm", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with japan and japanese details."),
        "mochi.jurassic-sunset-park": Entry(
            category: .nature, tags: ["dinosaur", "prehistoric", "dark"],
            keywords: ["dinosaur", "prehistoric", "sunset", "golden hour", "warm", "dark", "brown", "jurassic", "park"],
            blurb: "Dark keys with dinosaur and prehistoric details."),
        "mochi.kawaii-boba-tea": Entry(
            category: .cozy, tags: ["kawaii", "cute", "cream"],
            keywords: ["kawaii", "cute", "adorable", "boba", "bubble tea", "sweet", "tea", "drink", "warm", "cream", "orange", "pastel"],
            blurb: "Pastel cream keys with kawaii and cute details."),
        "mochi.kawaii-cosmic-study": Entry(
            category: .space, tags: ["kawaii", "cute", "purple"],
            keywords: ["kawaii", "cute", "adorable", "space", "cosmic", "galaxy", "stars", "desk", "study", "books", "purple", "pink"],
            blurb: "Pastel purple keys with kawaii and cute details."),
        "mochi.kawaii-ocean-night": Entry(
            category: .nature, tags: ["kawaii", "cute", "purple"],
            keywords: ["kawaii", "cute", "adorable", "ocean", "sea", "water", "night", "dark", "purple", "blue", "pastel"],
            blurb: "Pastel purple keys with kawaii and cute details."),
        "mochi.kawaii-strawberry-dream": Entry(
            category: .cute, tags: ["kawaii", "cute", "red"],
            keywords: ["kawaii", "cute", "adorable", "strawberry", "fruit", "sweet", "dreamy", "dreams", "soft", "red", "pink", "pastel"],
            blurb: "Pastel red keys with kawaii and cute details."),
        "mochi.kitebound-sunset": Entry(
            category: .dreamy, tags: ["kites", "sky", "orange"],
            keywords: ["kites", "sky", "sunset", "golden hour", "warm", "orange", "brown", "bright", "kitebound"],
            blurb: "Bright orange keys with kites and sky details."),
        "mochi.lavender-moon-garden": Entry(
            category: .nature, tags: ["lavender", "purple", "magenta"],
            keywords: ["lavender", "purple", "flowers", "moon", "night", "garden", "plants", "magenta", "pink", "pastel"],
            blurb: "Pastel magenta keys with lavender and purple details."),
        "mochi.lavender-paris-night": Entry(
            category: .elegant, tags: ["lavender", "purple", "purple"],
            keywords: ["lavender", "purple", "flowers", "paris", "french", "chic", "night", "dark", "pastel"],
            blurb: "Pastel purple keys with lavender and purple details."),
        "mochi.liquid-aurora": Entry(
            category: .space, tags: ["liquid", "chrome", "blue"],
            keywords: ["liquid", "chrome", "fluid", "aurora", "northern lights", "glow", "blue", "purple", "dark"],
            blurb: "Dark blue keys with liquid and chrome details."),
        "mochi.magenta-midnight-glow": Entry(
            category: .other, tags: ["magenta", "glow", "pink"],
            keywords: ["magenta", "glow", "bold", "midnight", "night", "dark", "pink", "bright"],
            blurb: "Bright pink keys with magenta and glow details."),
        "mochi.matcha-garden": Entry(
            category: .nature, tags: ["matcha", "tea", "cream"],
            keywords: ["matcha", "tea", "green", "garden", "flowers", "plants", "cream", "pastel"],
            blurb: "Pastel cream keys with matcha and tea details."),
        "mochi.meadow-morning": Entry(
            category: .nature, tags: ["meadow", "grass", "cream"],
            keywords: ["meadow", "grass", "flowers", "morning", "light", "calm", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with meadow and grass details."),
        "mochi.mermaid-dreamscape": Entry(
            category: .dreamy, tags: ["mermaid", "ocean", "purple"],
            keywords: ["mermaid", "ocean", "fantasy", "dreamy", "surreal", "purple", "magenta", "pastel", "dreamscape"],
            blurb: "Pastel purple keys with mermaid and ocean details."),
        "mochi.midnight-cafe": Entry(
            category: .cozy, tags: ["midnight", "night", "purple"],
            keywords: ["midnight", "night", "dark", "cafe", "coffee", "warm", "purple"],
            blurb: "Dark purple keys with midnight and night details."),
        "mochi.midnight-carnival": Entry(
            category: .cute, tags: ["midnight", "night", "dark"],
            keywords: ["midnight", "night", "dark", "carnival", "fair", "festival", "brown"],
            blurb: "Dark keys with midnight and night details."),
        "mochi.midnight-ocean-voyage": Entry(
            category: .nature, tags: ["midnight", "night", "dark"],
            keywords: ["midnight", "night", "dark", "ocean", "sea", "water", "voyage", "journey", "brown"],
            blurb: "Dark keys with midnight and night details."),
        "mochi.midnight-racing-garage": Entry(
            category: .other, tags: ["midnight", "night", "dark"],
            keywords: ["midnight", "night", "dark", "racing", "cars", "speed", "garage"],
            blurb: "Dark keys with midnight and night details."),
        "mochi.midnight-voyage": Entry(
            category: .other, tags: ["midnight", "night", "orange"],
            keywords: ["midnight", "night", "dark", "voyage", "journey", "sea", "orange", "brown", "bright"],
            blurb: "Bright orange keys with midnight and night details."),
        "mochi.miniature-greenhouse": Entry(
            category: .nature, tags: ["tiny", "miniature", "dark"],
            keywords: ["tiny", "miniature", "greenhouse", "plants", "glass", "dark", "brown"],
            blurb: "Dark keys with tiny and miniature details."),
        "mochi.moon-arcade-dreams": Entry(
            category: .cute, tags: ["moon", "night", "purple"],
            keywords: ["moon", "night", "arcade", "games", "retro", "dreamy", "dreams", "purple", "blue", "bright"],
            blurb: "Bright purple keys with moon and night details."),
        "mochi.moonlit-beach-escape": Entry(
            category: .nature, tags: ["moon", "night", "magenta"],
            keywords: ["moon", "night", "moonlight", "beach", "sand", "sea", "magenta", "purple", "bright", "moonlit", "escape"],
            blurb: "Bright magenta keys with moon and night details."),
        "mochi.moonlit-hydrangea": Entry(
            category: .nature, tags: ["moon", "night", "blue"],
            keywords: ["moon", "night", "moonlight", "flowers", "bloom", "blue", "dark", "moonlit", "hydrangea"],
            blurb: "Dark blue keys with moon and night details."),
        "mochi.moonlit-magic": Entry(
            category: .dreamy, tags: ["moon", "night", "orange"],
            keywords: ["moon", "night", "moonlight", "magic", "magical", "spells", "orange", "brown", "bright", "moonlit"],
            blurb: "Bright orange keys with moon and night details."),
        "mochi.moonlit-meow-cafe": Entry(
            category: .cozy, tags: ["moon", "night", "magenta"],
            keywords: ["moon", "night", "moonlight", "cat", "kitten", "animal", "cafe", "coffee", "warm", "magenta", "purple", "bright"],
            blurb: "Bright magenta keys with moon and night details."),
        "mochi.moonlit-potion-lab": Entry(
            category: .dreamy, tags: ["moon", "night", "purple"],
            keywords: ["moon", "night", "moonlight", "potions", "witch", "magic", "purple", "dark", "bright", "moonlit", "potion", "lab"],
            blurb: "Bright purple keys with moon and night details."),
        "mochi.mystery-at-dusk": Entry(
            category: .dreamy, tags: ["mysterious", "moody", "brown"],
            keywords: ["mysterious", "moody", "dusk", "evening", "brown", "orange", "bright", "mystery"],
            blurb: "Bright brown keys with mysterious and moody details."),
        "mochi.mystic-green-haven": Entry(
            category: .dreamy, tags: ["mystical", "magic", "cream"],
            keywords: ["mystical", "magic", "mysterious", "calm", "retreat", "cream", "brown", "bright", "mystic", "green", "haven"],
            blurb: "Bright cream keys with mystical and magic details."),
        "mochi.mystic-ocean-atelier": Entry(
            category: .nature, tags: ["mystical", "magic", "teal"],
            keywords: ["mystical", "magic", "mysterious", "ocean", "sea", "water", "atelier", "studio", "art", "teal", "green", "pastel"],
            blurb: "Pastel teal keys with mystical and magic details."),
        "mochi.neon-aquarium": Entry(
            category: .nature, tags: ["neon", "glow", "blue"],
            keywords: ["neon", "glow", "nightlife", "ocean", "fish", "underwater", "blue", "bright", "aquarium"],
            blurb: "Bright blue keys with neon and glow details."),
        "mochi.neon-code-haven": Entry(
            category: .other, tags: ["neon", "glow", "blue"],
            keywords: ["neon", "glow", "nightlife", "coding", "tech", "terminal", "calm", "retreat", "blue", "purple", "dark", "code"],
            blurb: "Dark blue keys with neon and glow details."),
        "mochi.neon-dream-district": Entry(
            category: .dreamy, tags: ["neon", "glow", "dark"],
            keywords: ["neon", "glow", "nightlife", "dreamy", "dreams", "soft", "dark", "purple", "dream", "district"],
            blurb: "Dark keys with neon and glow details."),
        "mochi.neon-racing-garage": Entry(
            category: .other, tags: ["neon", "glow", "dark"],
            keywords: ["neon", "glow", "nightlife", "racing", "cars", "speed", "garage", "dark", "red"],
            blurb: "Dark keys with neon and glow details."),
        "mochi.neon-roller-nights": Entry(
            category: .cute, tags: ["neon", "glow", "dark"],
            keywords: ["neon", "glow", "nightlife", "roller skating", "retro", "party", "night", "dark", "purple", "roller", "nights"],
            blurb: "Dark keys with neon and glow details."),
        "mochi.neural-dreamscape": Entry(
            category: .space, tags: ["futuristic", "tech", "purple"],
            keywords: ["futuristic", "tech", "glow", "dreamy", "surreal", "purple", "dark", "neural", "dreamscape"],
            blurb: "Dark purple keys with futuristic and tech details."),
        "mochi.oceanic-dreamscape": Entry(
            category: .nature, tags: ["ocean", "sea", "teal"],
            keywords: ["ocean", "sea", "water", "dreamy", "surreal", "teal", "green", "pastel", "oceanic", "dreamscape"],
            blurb: "Pastel teal keys with ocean and sea details."),
        "mochi.parisian-morning": Entry(
            category: .elegant, tags: ["paris", "french", "cream"],
            keywords: ["paris", "french", "chic", "morning", "light", "calm", "cream", "orange", "pastel", "parisian"],
            blurb: "Pastel cream keys with paris and french details."),
        "mochi.pastel-beyond": Entry(
            category: .dreamy, tags: ["pastel", "soft", "purple"],
            keywords: ["pastel", "soft", "horizon", "sky", "journey", "purple", "pink", "beyond"],
            blurb: "Pastel purple keys with pastel and soft details."),
        "mochi.pastel-lakeside-carnival": Entry(
            category: .nature, tags: ["pastel", "soft", "pink"],
            keywords: ["pastel", "soft", "lake", "water", "carnival", "fair", "festival", "pink", "magenta", "lakeside"],
            blurb: "Pastel pink keys with pastel and soft details."),
        "mochi.pastel-pink-sky": Entry(
            category: .dreamy, tags: ["pastel", "soft", "pink"],
            keywords: ["pastel", "soft", "sky", "clouds", "pink"],
            blurb: "Pastel pink keys with pastel and soft details."),
        "mochi.pastel-underwater": Entry(
            category: .nature, tags: ["pastel", "soft", "teal"],
            keywords: ["pastel", "soft", "ocean", "underwater", "fish", "teal", "bright"],
            blurb: "Bright teal keys with pastel and soft details."),
        "mochi.pirate-treasure-night": Entry(
            category: .other, tags: ["pirate", "treasure", "dark"],
            keywords: ["pirate", "treasure", "ship", "gold", "adventure", "night", "dark"],
            blurb: "Dark keys with pirate and treasure details."),
        "mochi.pixel-pet-dreams": Entry(
            category: .cute, tags: ["8bit", "pets", "purple"],
            keywords: ["pixel art", "retro game", "8bit", "pets", "animals", "cute", "dreamy", "dreams", "purple", "magenta", "pastel", "pixel"],
            blurb: "Pastel purple keys with 8bit and pets details."),
        "mochi.pocket-city-dreams": Entry(
            category: .cozy, tags: ["tiny", "miniature", "pink"],
            keywords: ["tiny", "miniature", "city", "buildings", "lights", "dreamy", "dreams", "pink", "red", "pastel", "pocket"],
            blurb: "Pastel pink keys with tiny and miniature details."),
        "mochi.pocket-cosmos": Entry(
            category: .space, tags: ["tiny", "miniature", "purple"],
            keywords: ["tiny", "miniature", "space", "cosmos", "stars", "purple", "blue", "pastel", "pocket"],
            blurb: "Pastel purple keys with tiny and miniature details."),
        "mochi.prehistoric-fossil-explorer": Entry(
            category: .nature, tags: ["dinosaur", "prehistoric", "brown"],
            keywords: ["dinosaur", "prehistoric", "fossil", "explorer", "adventure", "journey", "brown", "cream", "bright"],
            blurb: "Bright brown keys with dinosaur and prehistoric details."),
        "mochi.prismatic-jelly-dreams": Entry(
            category: .cute, tags: ["prism", "rainbow", "pink"],
            keywords: ["prism", "rainbow", "iridescent", "jelly", "squishy", "candy", "dreamy", "dreams", "pink", "purple", "pastel", "prismatic"],
            blurb: "Pastel pink keys with prism and rainbow details."),
        "mochi.puzzlewood-adventures": Entry(
            category: .nature, tags: ["forest", "woods", "blue"],
            keywords: ["forest", "woods", "adventure", "journey", "explore", "blue", "brown", "bright", "puzzlewood", "adventures"],
            blurb: "Bright blue keys with forest and woods details."),
        "mochi.reflective-dreamworld": Entry(
            category: .dreamy, tags: ["reflection", "mirror", "purple"],
            keywords: ["reflection", "mirror", "surreal", "purple", "magenta", "pastel", "reflective", "dreamworld"],
            blurb: "Pastel purple keys with reflection and mirror details."),
        "mochi.retro-arcade": Entry(
            category: .cute, tags: ["retro", "nostalgia", "brown"],
            keywords: ["retro", "nostalgia", "vintage", "arcade", "games", "brown", "dark"],
            blurb: "Dark brown keys with retro and nostalgia details."),
        "mochi.royal-sunset-atelier": Entry(
            category: .elegant, tags: ["royal", "regal", "red"],
            keywords: ["royal", "regal", "luxury", "sunset", "golden hour", "warm", "atelier", "studio", "art", "red", "brown", "dark"],
            blurb: "Dark red keys with royal and regal details."),
        "mochi.ruins-and-relics": Entry(
            category: .other, tags: ["ruins", "ancient", "orange"],
            keywords: ["ruins", "ancient", "adventure", "treasure", "orange", "brown", "bright", "relics"],
            blurb: "Bright orange keys with ruins and ancient details."),
        "mochi.sakura-night-kawaii-landscape": Entry(
            category: .cute, tags: ["sakura", "spring", "pink"],
            keywords: ["sakura", "cherry blossom", "spring", "night", "dark", "kawaii", "cute", "adorable", "pink", "pastel", "landscape"],
            blurb: "Pastel pink keys with sakura and spring details."),
        "mochi.sakura-serenity": Entry(
            category: .dreamy, tags: ["sakura", "spring", "cream"],
            keywords: ["sakura", "cherry blossom", "spring", "calm", "peaceful", "soft", "cream", "brown", "pastel", "serenity"],
            blurb: "Pastel cream keys with sakura and spring details."),
        "mochi.sakura-train": Entry(
            category: .cozy, tags: ["sakura", "spring", "purple"],
            keywords: ["sakura", "cherry blossom", "spring", "train", "travel", "journey", "purple", "magenta", "bright"],
            blurb: "Bright purple keys with sakura and spring details."),
        "mochi.seaside-postcard": Entry(
            category: .nature, tags: ["beach", "coast", "blue"],
            keywords: ["beach", "coast", "sea", "travel", "postcard", "summer", "blue", "cream", "pastel", "seaside"],
            blurb: "Pastel blue keys with beach and coast details."),
        "mochi.skyward-explorer": Entry(
            category: .space, tags: ["sky", "clouds", "cream"],
            keywords: ["sky", "clouds", "flight", "explorer", "adventure", "journey", "cream", "brown", "pastel", "skyward"],
            blurb: "Pastel cream keys with sky and clouds details."),
        "mochi.skyward-reverie": Entry(
            category: .space, tags: ["sky", "clouds", "purple"],
            keywords: ["sky", "clouds", "flight", "dreamy", "soft", "quiet", "purple", "magenta", "pastel", "skyward", "reverie"],
            blurb: "Pastel purple keys with sky and clouds details."),
        "mochi.starlit-90s-haven": Entry(
            category: .space, tags: ["stars", "night", "purple"],
            keywords: ["stars", "night", "90s", "retro", "nostalgia", "calm", "retreat", "purple", "magenta", "pastel", "starlit", "haven"],
            blurb: "Pastel purple keys with stars and night details."),
        "mochi.starlit-cozy-village": Entry(
            category: .space, tags: ["stars", "night", "pink"],
            keywords: ["stars", "night", "cozy", "warm", "comfy", "village", "houses", "town", "pink", "cream", "pastel", "starlit"],
            blurb: "Pastel pink keys with stars and night details."),
        "mochi.starlit-disco-reverie": Entry(
            category: .space, tags: ["stars", "night", "dark"],
            keywords: ["stars", "night", "disco", "party", "lights", "dreamy", "soft", "quiet", "dark", "magenta", "starlit", "reverie"],
            blurb: "Dark keys with stars and night details."),
        "mochi.starlit-dream-cafe": Entry(
            category: .space, tags: ["stars", "night", "pink"],
            keywords: ["stars", "night", "dreamy", "dreams", "soft", "cafe", "coffee", "warm", "pink", "magenta", "pastel", "starlit"],
            blurb: "Pastel pink keys with stars and night details."),
        "mochi.starlit-orbit": Entry(
            category: .space, tags: ["stars", "night", "purple"],
            keywords: ["stars", "night", "space", "orbit", "planets", "purple", "blue", "pastel", "starlit"],
            blurb: "Pastel purple keys with stars and night details."),
        "mochi.sunset-mirage": Entry(
            category: .elegant, tags: ["sunset", "warm", "brown"],
            keywords: ["sunset", "golden hour", "warm", "desert", "haze", "brown", "orange", "bright", "mirage"],
            blurb: "Bright brown keys with sunset and warm details."),
        "mochi.sunset-music-studio": Entry(
            category: .elegant, tags: ["sunset", "warm", "orange"],
            keywords: ["sunset", "golden hour", "warm", "music", "studio", "sound", "orange", "red", "bright"],
            blurb: "Bright orange keys with sunset and warm details."),
        "mochi.sunset-storybook-journey": Entry(
            category: .cozy, tags: ["sunset", "warm", "cream"],
            keywords: ["sunset", "golden hour", "warm", "storybook", "fairytale", "journey", "travel", "cream", "orange", "bright"],
            blurb: "Bright cream keys with sunset and warm details."),
        "mochi.sweetdream-carnival": Entry(
            category: .cute, tags: ["sweet", "dreamy", "pink"],
            keywords: ["sweet", "dreamy", "candy", "carnival", "fair", "festival", "pink", "magenta", "pastel", "sweetdream"],
            blurb: "Pastel pink keys with sweet and dreamy details."),
        "mochi.the-wanderers-cabin": Entry(
            category: .cozy, tags: ["travel", "cabin", "brown"],
            keywords: ["travel", "cabin", "wood", "warm", "brown", "dark", "wanderers"],
            blurb: "Dark brown keys with travel and cabin details."),
        "mochi.tidebound-atelier": Entry(
            category: .nature, tags: ["sea", "water", "green"],
            keywords: ["sea", "water", "coast", "atelier", "studio", "art", "green", "dark", "tidebound"],
            blurb: "Dark green keys with sea and water details."),
        "mochi.toymakers-memories": Entry(
            category: .cute, tags: ["toys", "playful", "brown"],
            keywords: ["toys", "playful", "workshop", "brown", "orange", "bright", "toymakers", "memories"],
            blurb: "Bright brown keys with toys and playful details."),
        "mochi.velvet-reel-reverie": Entry(
            category: .dreamy, tags: ["velvet", "luxury", "orange"],
            keywords: ["velvet", "luxury", "rich", "cinema", "film", "retro", "dreamy", "soft", "quiet", "orange", "brown", "bright"],
            blurb: "Bright orange keys with velvet and luxury details."),
        "mochi.vintage-writer-evening": Entry(
            category: .elegant, tags: ["vintage", "retro", "orange"],
            keywords: ["vintage", "retro", "classic", "writing", "desk", "evening", "calm", "orange", "brown", "bright", "writer"],
            blurb: "Bright orange keys with vintage and retro details."),
        "mochi.wanderlight-loft": Entry(
            category: .cozy, tags: ["travel", "warm", "pink"],
            keywords: ["travel", "warm", "lamp", "loft", "room", "home", "pink", "red", "pastel", "wanderlight"],
            blurb: "Pastel pink keys with travel and warm details."),
        "mochi.wanderlust-scrapbook": Entry(
            category: .cozy, tags: ["travel", "adventure", "orange"],
            keywords: ["travel", "adventure", "memories", "scrapbook", "paper", "orange", "brown", "bright", "wanderlust"],
            blurb: "Bright orange keys with travel and adventure details."),
        "mochi.whimsical-world": Entry(
            category: .dreamy, tags: ["whimsical", "playful", "cream"],
            keywords: ["whimsical", "playful", "magic", "world", "scenery", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with whimsical and playful details."),
        "mochi.whispering-lake-cottage": Entry(
            category: .nature, tags: ["quiet", "soft", "cream"],
            keywords: ["quiet", "soft", "calm", "lake", "water", "cottage", "cottagecore", "home", "cream", "pink", "pastel", "whispering"],
            blurb: "Pastel cream keys with quiet and soft details."),
        "mochi.whispering-moon-harbor": Entry(
            category: .dreamy, tags: ["quiet", "soft", "purple"],
            keywords: ["quiet", "soft", "calm", "moon", "night", "purple", "magenta", "pastel", "whispering", "harbor"],
            blurb: "Pastel purple keys with quiet and soft details."),
        "mochi.whispering-mushroom-cottage": Entry(
            category: .nature, tags: ["quiet", "soft", "cream"],
            keywords: ["quiet", "soft", "calm", "mushrooms", "forest", "cottage", "cottagecore", "home", "cream", "gold", "bright", "whispering"],
            blurb: "Bright cream keys with quiet and soft details."),
        "mochi.whispers-of-the-sewing-hearth": Entry(
            category: .cozy, tags: ["quiet", "soft", "orange"],
            keywords: ["quiet", "soft", "sewing", "craft", "home", "hearth", "fire", "warm", "orange", "brown", "bright", "whispers"],
            blurb: "Bright orange keys with quiet and soft details."),
        "mochi.willow-moon-cottage": Entry(
            category: .nature, tags: ["tree", "willow", "cream"],
            keywords: ["tree", "willow", "moon", "night", "cottage", "cottagecore", "home", "cream", "brown", "pastel"],
            blurb: "Pastel cream keys with tree and willow details."),
        "mochi.witchy-potion-shop": Entry(
            category: .dreamy, tags: ["witch", "magic", "purple"],
            keywords: ["witch", "magic", "spooky", "potions", "shop", "store", "purple", "magenta", "pastel", "witchy", "potion"],
            blurb: "Pastel purple keys with witch and magic details."),
        "mochi.zen-garden": Entry(
            category: .nature, tags: ["zen", "calm", "cream"],
            keywords: ["zen", "calm", "japanese", "garden", "flowers", "plants", "cream", "green", "pastel"],
            blurb: "Pastel cream keys with zen and calm details."),
    ]

    static func entry(for id: String) -> Entry? { byID[id] }
}
